### ISSUE TITLE
Wrong seldepth

### ISSUE THREAD

**Issue by Matthies** [rosenthj/Winter#4]
Small issue: 0.4 seems to send wrong seldepth info. The values are constant per move and sometimes > 100. Seems to decrease with the moves like a counter to 50 moves draw but not exactly.

**Comment by rosenthj** [comment]
Thank you for raising the issue! I will take a look into it!

**Comment by rosenthj** [comment]
This is fixed in todays updated release, Winter 0.4a. Nothing else (aside from version name and removing an unused variable) has been changed in this new version.

Thanks again!
