### ISSUE TITLE
Question about compilation

### ISSUE THREAD

**Issue by SzotsGabor** [rosenthj/Winter#72]
Hi Jonathan,

I have successfully compiled Winter for Windows. However, I am not sure if I did it correctly.  I see there is a net f192,,,.bin included in the package but how is that used during compilation? I see no reference for it in the makefile. When running the exe, in the options I can't see an option for the net. Is that included in the binary somehow?

**Comment by rosenthj** [comment]
Hi Gabor,

So, at the moment I have it hardcoded in src/evaluate.cc on line 9 to include the net.
I will probably be changing that soon, so it will be more like other programs which let you specify it in the makefile. Currently, I don't think Winter nets are compatible with other engines (fully connected net with 772 inputs, 192 hidden units, and 3 outputs). I may add support for other network architectures for people, wanting to mix and match networks from different engines, in the future.

**Comment by SzotsGabor** [comment]
Thanks for the explanation. I don't intend to mix networks, I was only afraid that my compile did not include the net. Anyway, yours is a little bit faster so I'm going to use that (or, rather, I am already using it in a gauntlet for the CCRL blitz list).
